// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gewepxdvrirptrbedfat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdld2VweGR2cmlycHRyYmVkZmF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwOTU4NjEsImV4cCI6MjA2NTY3MTg2MX0.eqWJVMOu6OS9fqDqfPISBKixIiSX85Npr0ejarrJuTw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);